class CityCoordinate {
  final String name;
  final String region;
  final double latitude;
  final double longitude;

  const CityCoordinate({
    required this.name,
    required this.region,
    required this.latitude,
    required this.longitude,
  });
}

const List<CityCoordinate> cityCoordinates = [
  CityCoordinate(
    name: 'Adana',
    region: 'Akdeniz',
    latitude: 36.9864,
    longitude: 35.3253,
  ),
  CityCoordinate(
    name: 'Adıyaman',
    region: 'Güneydoğu Anadolu',
    latitude: 37.7640,
    longitude: 38.2769,
  ),
  CityCoordinate(
    name: 'Afyonkarahisar',
    region: 'Ege',
    latitude: 38.7569,
    longitude: 30.5387,
  ),
  CityCoordinate(
    name: 'Ağrı',
    region: 'Doğu Anadolu',
    latitude: 39.7191,
    longitude: 43.0505,
  ),
  CityCoordinate(
    name: 'Aksaray',
    region: 'İç Anadolu',
    latitude: 38.3705,
    longitude: 34.0269,
  ),
  CityCoordinate(
    name: 'Amasya',
    region: 'Karadeniz',
    latitude: 40.6503,
    longitude: 35.8329,
  ),
  CityCoordinate(
    name: 'Ankara',
    region: 'İç Anadolu',
    latitude: 39.9208,
    longitude: 32.8540,
  ),
  CityCoordinate(
    name: 'Antalya',
    region: 'Akdeniz',
    latitude: 36.9010,
    longitude: 30.6955,
  ),
  CityCoordinate(
    name: 'Ardahan',
    region: 'Doğu Anadolu',
    latitude: 41.1103,
    longitude: 42.7036,
  ),
  CityCoordinate(
    name: 'Artvin',
    region: 'Karadeniz',
    latitude: 41.1831,
    longitude: 41.8287,
  ),
  CityCoordinate(
    name: 'Aydın',
    region: 'Ege',
    latitude: 37.8484,
    longitude: 27.8436,
  ),
  CityCoordinate(
    name: 'Balıkesir',
    region: 'Marmara',
    latitude: 39.6474,
    longitude: 27.8880,
  ),
  CityCoordinate(
    name: 'Bartın',
    region: 'Karadeniz',
    latitude: 41.6338,
    longitude: 32.3384,
  ),
  CityCoordinate(
    name: 'Batman',
    region: 'Güneydoğu Anadolu',
    latitude: 37.8836,
    longitude: 41.1277,
  ),
  CityCoordinate(
    name: 'Bayburt',
    region: 'Karadeniz',
    latitude: 40.2557,
    longitude: 40.2241,
  ),
  CityCoordinate(
    name: 'Bilecik',
    region: 'Marmara',
    latitude: 40.1435,
    longitude: 29.9753,
  ),
  CityCoordinate(
    name: 'Bingöl',
    region: 'Doğu Anadolu',
    latitude: 38.8854,
    longitude: 40.4966,
  ),
  CityCoordinate(
    name: 'Bitlis',
    region: 'Doğu Anadolu',
    latitude: 38.3996,
    longitude: 42.1080,
  ),
  CityCoordinate(
    name: 'Bolu',
    region: 'Karadeniz',
    latitude: 40.7333,
    longitude: 31.6110,
  ),
  CityCoordinate(
    name: 'Burdur',
    region: 'Akdeniz',
    latitude: 37.7203,
    longitude: 30.2908,
  ),
  CityCoordinate(
    name: 'Bursa',
    region: 'Marmara',
    latitude: 40.1960,
    longitude: 29.0600,
  ),
  CityCoordinate(
    name: 'Çanakkale',
    region: 'Marmara',
    latitude: 40.1553,
    longitude: 26.4142,
  ),
  CityCoordinate(
    name: 'Çankırı',
    region: 'İç Anadolu',
    latitude: 40.6002,
    longitude: 33.6163,
  ),
  CityCoordinate(
    name: 'Çorum',
    region: 'Karadeniz',
    latitude: 40.5506,
    longitude: 34.9556,
  ),
  CityCoordinate(
    name: 'Denizli',
    region: 'Ege',
    latitude: 37.7830,
    longitude: 29.0963,
  ),
  CityCoordinate(
    name: 'Diyarbakır',
    region: 'Güneydoğu Anadolu',
    latitude: 37.9144,
    longitude: 40.2306,
  ),
  CityCoordinate(
    name: 'Düzce',
    region: 'Karadeniz',
    latitude: 40.8438,
    longitude: 31.1565,
  ),
  CityCoordinate(
    name: 'Edirne',
    region: 'Marmara',
    latitude: 41.6771,
    longitude: 26.5557,
  ),
  CityCoordinate(
    name: 'Elazığ',
    region: 'Doğu Anadolu',
    latitude: 38.6748,
    longitude: 39.2225,
  ),
  CityCoordinate(
    name: 'Erzincan',
    region: 'Doğu Anadolu',
    latitude: 39.7500,
    longitude: 39.5000,
  ),
  CityCoordinate(
    name: 'Erzurum',
    region: 'Doğu Anadolu',
    latitude: 39.9055,
    longitude: 41.2658,
  ),
  CityCoordinate(
    name: 'Eskişehir',
    region: 'İç Anadolu',
    latitude: 39.7767,
    longitude: 30.5206,
  ),
  CityCoordinate(
    name: 'Gaziantep',
    region: 'Güneydoğu Anadolu',
    latitude: 37.0662,
    longitude: 37.3833,
  ),
  CityCoordinate(
    name: 'Giresun',
    region: 'Karadeniz',
    latitude: 40.9128,
    longitude: 38.3895,
  ),
  CityCoordinate(
    name: 'Gümüşhane',
    region: 'Karadeniz',
    latitude: 40.4603,
    longitude: 39.4814,
  ),
  CityCoordinate(
    name: 'Hakkari',
    region: 'Doğu Anadolu',
    latitude: 37.5744,
    longitude: 43.7408,
  ),
  CityCoordinate(
    name: 'Hatay',
    region: 'Akdeniz',
    latitude: 36.2023,
    longitude: 36.1613,
  ),
  CityCoordinate(
    name: 'Iğdır',
    region: 'Doğu Anadolu',
    latitude: 39.9237,
    longitude: 44.0450,
  ),
  CityCoordinate(
    name: 'Isparta',
    region: 'Akdeniz',
    latitude: 37.7648,
    longitude: 30.5566,
  ),
  CityCoordinate(
    name: 'İstanbul',
    region: 'Marmara',
    latitude: 41.0082,
    longitude: 28.9784,
  ),
  CityCoordinate(
    name: 'İzmir',
    region: 'Ege',
    latitude: 38.4192,
    longitude: 27.1287,
  ),
  CityCoordinate(
    name: 'Kahramanmaraş',
    region: 'Akdeniz',
    latitude: 37.5753,
    longitude: 36.9228,
  ),
  CityCoordinate(
    name: 'Karabük',
    region: 'Karadeniz',
    latitude: 41.2061,
    longitude: 32.6204,
  ),
  CityCoordinate(
    name: 'Karaman',
    region: 'İç Anadolu',
    latitude: 37.1811,
    longitude: 33.2150,
  ),
  CityCoordinate(
    name: 'Kars',
    region: 'Doğu Anadolu',
    latitude: 40.6013,
    longitude: 43.0975,
  ),
  CityCoordinate(
    name: 'Kastamonu',
    region: 'Karadeniz',
    latitude: 41.3887,
    longitude: 33.7827,
  ),
  CityCoordinate(
    name: 'Kayseri',
    region: 'İç Anadolu',
    latitude: 38.7205,
    longitude: 35.4826,
  ),
  CityCoordinate(
    name: 'Kırıkkale',
    region: 'İç Anadolu',
    latitude: 39.8468,
    longitude: 33.5153,
  ),
  CityCoordinate(
    name: 'Kırklareli',
    region: 'Marmara',
    latitude: 41.7351,
    longitude: 27.2252,
  ),
  CityCoordinate(
    name: 'Kırşehir',
    region: 'İç Anadolu',
    latitude: 39.1461,
    longitude: 34.1606,
  ),
  CityCoordinate(
    name: 'Kilis',
    region: 'Güneydoğu Anadolu',
    latitude: 36.7165,
    longitude: 37.1147,
  ),
  CityCoordinate(
    name: 'Kocaeli',
    region: 'Marmara',
    latitude: 40.7654,
    longitude: 29.9408,
  ),
  CityCoordinate(
    name: 'Konya',
    region: 'İç Anadolu',
    latitude: 37.8746,
    longitude: 32.4932,
  ),
  CityCoordinate(
    name: 'Kütahya',
    region: 'Ege',
    latitude: 39.4192,
    longitude: 29.9857,
  ),
  CityCoordinate(
    name: 'Malatya',
    region: 'Doğu Anadolu',
    latitude: 38.3552,
    longitude: 38.3095,
  ),
  CityCoordinate(
    name: 'Manisa',
    region: 'Ege',
    latitude: 38.6191,
    longitude: 27.4289,
  ),
  CityCoordinate(
    name: 'Mardin',
    region: 'Güneydoğu Anadolu',
    latitude: 37.3122,
    longitude: 40.7351,
  ),
  CityCoordinate(
    name: 'Mersin',
    region: 'Akdeniz',
    latitude: 36.8121,
    longitude: 34.6415,
  ),
  CityCoordinate(
    name: 'Muğla',
    region: 'Ege',
    latitude: 37.2153,
    longitude: 28.3636,
  ),
  CityCoordinate(
    name: 'Muş',
    region: 'Doğu Anadolu',
    latitude: 38.7432,
    longitude: 41.5065,
  ),
  CityCoordinate(
    name: 'Nevşehir',
    region: 'İç Anadolu',
    latitude: 38.6244,
    longitude: 34.7240,
  ),
  CityCoordinate(
    name: 'Niğde',
    region: 'İç Anadolu',
    latitude: 37.9667,
    longitude: 34.6833,
  ),
  CityCoordinate(
    name: 'Ordu',
    region: 'Karadeniz',
    latitude: 40.9839,
    longitude: 37.8764,
  ),
  CityCoordinate(
    name: 'Osmaniye',
    region: 'Akdeniz',
    latitude: 37.0742,
    longitude: 36.2478,
  ),
  CityCoordinate(
    name: 'Rize',
    region: 'Karadeniz',
    latitude: 41.0201,
    longitude: 40.5234,
  ),
  CityCoordinate(
    name: 'Sakarya',
    region: 'Marmara',
    latitude: 40.7731,
    longitude: 30.3948,
  ),
  CityCoordinate(
    name: 'Samsun',
    region: 'Karadeniz',
    latitude: 41.2867,
    longitude: 36.3300,
  ),
  CityCoordinate(
    name: 'Siirt',
    region: 'Güneydoğu Anadolu',
    latitude: 37.9274,
    longitude: 41.9423,
  ),
  CityCoordinate(
    name: 'Sinop',
    region: 'Karadeniz',
    latitude: 42.0268,
    longitude: 35.1628,
  ),
  CityCoordinate(
    name: 'Sivas',
    region: 'İç Anadolu',
    latitude: 39.7477,
    longitude: 37.0179,
  ),
  CityCoordinate(
    name: 'Şanlıurfa',
    region: 'Güneydoğu Anadolu',
    latitude: 37.1674,
    longitude: 38.7955,
  ),
  CityCoordinate(
    name: 'Şırnak',
    region: 'Güneydoğu Anadolu',
    latitude: 37.5228,
    longitude: 42.4594,
  ),
  CityCoordinate(
    name: 'Tekirdağ',
    region: 'Marmara',
    latitude: 40.9781,
    longitude: 27.5117,
  ),
  CityCoordinate(
    name: 'Tokat',
    region: 'Karadeniz',
    latitude: 40.3167,
    longitude: 36.5500,
  ),
  CityCoordinate(
    name: 'Trabzon',
    region: 'Karadeniz',
    latitude: 41.0027,
    longitude: 39.7168,
  ),
  CityCoordinate(
    name: 'Tunceli',
    region: 'Doğu Anadolu',
    latitude: 39.1083,
    longitude: 39.5483,
  ),
  CityCoordinate(
    name: 'Uşak',
    region: 'Ege',
    latitude: 38.6795,
    longitude: 29.4054,
  ),
  CityCoordinate(
    name: 'Van',
    region: 'Doğu Anadolu',
    latitude: 38.5084,
    longitude: 43.3745,
  ),
  CityCoordinate(
    name: 'Yalova',
    region: 'Marmara',
    latitude: 40.6583,
    longitude: 29.2700,
  ),
  CityCoordinate(
    name: 'Yozgat',
    region: 'İç Anadolu',
    latitude: 39.8206,
    longitude: 34.8095,
  ),
  CityCoordinate(
    name: 'Zonguldak',
    region: 'Karadeniz',
    latitude: 41.4519,
    longitude: 31.7906,
  ),
];

CityCoordinate? findCityCoordinate(String name) {
  for (final city in cityCoordinates) {
    if (city.name == name) return city;
  }
  return null;
}
